//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNLTHD2018.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETPHIEUMUONs = new HashSet<CHITIETPHIEUMUON>();
            this.TRASACHes = new HashSet<TRASACH>();
            this.VIPHAMs = new HashSet<VIPHAM>();
        }
    
        public string MaSach { get; set; }
        public int MaLoaiSach { get; set; }
        public string TenSach { get; set; }
        public string TacGia { get; set; }
        public string MaNXB { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> NamXB { get; set; }
        public string NoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        public virtual LOAISACH LOAISACH { get; set; }
        public virtual NHAXB NHAXB { get; set; }
        public virtual TINHTRANG TINHTRANG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRASACH> TRASACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIPHAM> VIPHAMs { get; set; }
    }
}
