//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNLTHD2018.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPHAM
    {
        public string MaDG { get; set; }
        public string MaSach { get; set; }
        public string NoiDungVP { get; set; }
        public string HinhThucXP { get; set; }
        public string MucPhat { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
